// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gopwhicebedqivdmrmks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvcHdoaWNlYmVkcWl2ZG1ybWtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MTA4MDQsImV4cCI6MjA2MjM4NjgwNH0.Pu9W7t4chigD3NOq0gj_AhGs5sohNjPusk4bacaP9-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);